mysite/inventory/urls.py
from django.urls import path

from inventory import views

app_name = 'inventory'

urlpatterns = [
    path('', views.item_list, name='item_list'),
    path('detail/<int:pk>', views.item_detail, name='item_detail'),
    path('create/', views.item_create, name='item_create'),
    path('update/<int:pk>', views.item_update, name='item_update'),
    path('delete/<int:pk>', views.item_delete, name='item_delete'),
    path('plus/<int:pk>', views.item_plus, name='item_plus'),
    path('minus/<int:pk>', views.item_minus, name='item_minus'),

    path('company/', views.company_list, name='company_list'),
    path('company/detail/<int:pk>', views.company_detail, name='company_detail'),
    path('company/create/', views.company_create, name='company_create'),
    path('company/update/<int:pk>', views.company_update, name='company_update'),
    path('company/delete/<int:pk>', views.company_delete, name='company_delete'),
]

mysite/mysite/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('inventory.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/inventory/models.py
from django.db import models
from django.urls import reverse

from mysite.utils import uuid_upload_to


class Company(models.Model):
    name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=20)
    address = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Item(models.Model):
    name = models.CharField(max_length=200)
    photo = models.ImageField(blank=True, upload_to=uuid_upload_to)
    desc = models.TextField(blank=True)
    price = models.PositiveIntegerField()
    remain = models.PositiveIntegerField(default=0)
    company = models.ForeignKey(Company, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('inventory:item_detail', kwargs={'pk': self.pk})

mysite/inventory/forms.py
from django import forms

from inventory.models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

mysite/inventory/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import CreateView, UpdateView

from inventory.forms import ItemForm
from inventory.models import Item, Company


def item_list(request):
    qs = Item.objects.all()
    return render(request, 'inventory/item_list.html', {
        'item_list': qs,
    })


def item_detail(request, pk):
    item = get_object_or_404(Item, pk=pk)
    company = get_object_or_404(Company, name=item.company)
    return render(request, 'inventory/item_detail.html', {
        'item': item,
        'company': company,
    })


item_create = CreateView.as_view(model=Item, form_class=ItemForm)
item_update = UpdateView.as_view(model=Item, form_class=ItemForm)


def item_delete(request, pk):
    item = Item.objects.get(pk=pk)
    item.delete()
    return redirect('inventory:item_list')


def item_plus(request, pk):
    item = Item.objects.get(pk=pk)
    item.remain += 1
    item.save()
    return redirect('inventory:item_list')


def item_minus(request, pk):
    item = Item.objects.get(pk=pk)
    if item.remain != 0:
        item.remain -= 1
        item.save()
    return redirect('inventory:item_list')


def company_list(request):
    qs = Company.objects.all()
    return render(request, 'inventory/company_list.html', {
        'company_list': qs,
    })


def company_detail(request, pk):
    company = get_object_or_404(Company, pk=pk)
    qs = Item.objects.filter(company=company)
    return render(request, 'inventory/company_detail.html', {
        'company': company,
        'item_list': qs,
    })


def company_create(request):
    if request.method == 'GET':
        return render(request, 'inventory/company_form.html', {})
    elif request.method == 'POST':
        name = request.POST['name']
        phone_number = request.POST['phone_number']
        address = request.POST['address']
        company = Company.objects.create(name=name, phone_number=phone_number, address=address)
        return redirect('inventory:company_detail', company.id)


def company_update(request, pk):
    company = Company.objects.get(pk=pk)

    if request.method == 'GET':
        return render(request, 'inventory/company_update.html', {'company': company})

    elif request.method == 'POST':
        name = request.POST['name']
        phone_number = request.POST['phone_number']
        address = request.POST['address']
        company.name = name
        company.phone_number = phone_number
        company.address = address
        company.save()
        return redirect('inventory:company_detail', company.id)


def company_delete(request, pk):
    company = Company.objects.get(pk=pk)
    company.delete()
    return redirect('inventory:company_list')

mysite/inventory/templates/inventory/company_detail.html
{% extends "inventory/layout.html" %}

{% block content %}
    <h2>{{ company.name }}</h2>

    {% if company.phone_number %}
        <p>
            {{ company.phone_number }}
        </p>
    {% endif %}
    {% if company.address %}
        <p>
            {{ company.address }}
        </p>
    {% endif %}
    <hr/>
    <h4>거래 상품 목록</h4>
    {% for item in item_list %}
        <a href="{% url "inventory:item_detail" item.pk %}">{{ item.name }}<br/></a>
    {% endfor %}
    <hr/>
    <a href="{% url "inventory:company_update" company.pk %}">수정</a><br/>
    <a href="{% url "inventory:company_delete" company.pk %}">삭제</a><br/>
    <a href="{% url "inventory:company_list" %}">목록</a><br/><br/>

{% endblock %}

mysite/inventory/templates/inventory/company_form.html
{% extends "inventory/layout.html" %}

{% block content %}
    <h2>거래처 등록</h2>

    <form action="" method="POST" >
        {% csrf_token %}
        <p>이름: <input type="text" name="name"></p>
        <p>전화번호: <input type="text" name="phone_number"></p>
        <p>주소: <input type="text" name="address"></p>
        <input type="submit" value="등록" class="btn btn-primary"/>
    </form>

{% endblock %}

mysite/inventory/templates/inventory/company_list.html
{% extends "inventory/layout.html" %}
{% block content %}
    {{ block.super }}
    <div class="row row-cols-1 row-cols-md-3">
        {% for company in company_list %}
        <div class="col mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'inventory:company_detail' company.id %}">{{ company.name }}</a></h5>
                    <p class="card-text">
                        {{ company.phone_number }}<br><br>
                        {{ company.address }}<br>
                    </p>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

{% endblock %}

mysite/inventory/templates/inventory/company_update.html
{% extends "inventory/layout.html" %}

{% block content %}
    <h2>거래처 수정</h2>

    <form action="" method="POST" >
        {% csrf_token %}
        <p>이름: <input type="text" name="name" value="{{ company.name }}"></p>
        <p>전화번호: <input type="text" name="phone_number" value="{{ company.phone_number }}"></p>
        <p>주소: <input type="text" name="address" value="{{ company.address }}"></p>
        <input type="submit" value="등록" class="btn btn-primary"/>
    </form>
{% endblock %}

mysite/inventory/templates/inventory/item_detail.html
{% extends "inventory/layout.html" %}
{% load humanize %}

{% block content %}
    {% if item.photo %}
        <img src="{{ item.photo.url }}" alt="img" width="100%"/>
    {% else %}
        <img src="https://rimage.gnst.jp/livejapan.com/public/img/common/noimage.jpg?20191216050037" alt="img"/>
    {% endif %}

    <h2>{{ item.name }}</h2>

    가격: {{ item.price|intcomma }}<br /><br />
    수량: {{ item.remain }}<br /><br />
    제품 설명:<br/>{{ item.desc|linebreaksbr }}<br /><br />
    <a href="{% url "inventory:company_detail" company.pk %}">
     거래처: {{ item.company }}
    </a>

    <hr/>
    <a href="{% url "inventory:item_update" item.pk %}">수정</a><br/>
    <a href="{% url "inventory:item_delete" item.pk %}">삭제</a><br/>
    <a href="{% url "inventory:item_list" %}">목록</a><br/><br/>
{% endblock %}

mysite/inventory/templates/inventory/item_form.html
{% extends "inventory/layout.html" %}

{% block content %}
    <h2>거래처 등록</h2>
    <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
        <table class="table">
            {{ form.as_table }}
        </table>
        <input type="submit" value="등록" class="btn btn-primary"/>
    </form>
    <br/><br/><br/>
{% endblock %}

mysite/inventory/templates/inventory/item_list.html
{% extends "inventory/layout.html" %}
{% load humanize %}

{% block content %}
    {{ block.super }}
    <div class="row row-cols-1 row-cols-md-3">
        {% for item in item_list %}
            <div class="col mb-4">
                <div class="card">
                    {% if item.photo %}
                        <img src="{{ item.photo.url }}" class="card-img-top" alt="img" width="100%"/>
                    {% else %}
                        <img src="https://rimage.gnst.jp/livejapan.com/public/img/common/noimage.jpg?20191216050037"
                             class="card-img-top" alt="img"/>
                    {% endif %}

                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'inventory:item_detail' item.id %}">{{ item.name }}</a>
                        </h5>
                        <p class="card-text">
                            가격 : {{ item.price|intcomma }}<br><br>
                            남은 수량 : {{ item.remain }}<br><br>
                        <form action="{% url "inventory:item_plus" item.pk %}" method="post">
                        {% csrf_token %}
                            <input type="submit" value="+">
                        </form>
                        <form action="{% url "inventory:item_minus" item.pk %}" method="post">
                        {% csrf_token %}
                            <input type="submit" value="- ">
                        </form>
                        </p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    </ul>

{% endblock %}